import { useLanguage } from "@/contexts/LanguageContext";
import { getSettingsText } from "@/i18n/settingsTranslations";
const extra:Record<string,Record<string,string>>={
 fr:{likes:"Mentions J'aime",shares:"Partages",suggestions:"Suggestions",shareCopied:"Lien AfriTok copié",shareError:"Impossible de partager AfriTok",creditsInfo:"Les crédits du projet sont disponibles dans le dépôt AfriTok.",rights:"Tous droits réservés.",adminRestricted:"Accès restreint aux administrateurs.",warnings:"Mes avertissements",warningsLoading:"Chargement de vos avertissements...",warningsError:"Impossible de charger vos avertissements.",warningsDesc:"Consultez les avertissements reçus de l'administration.",noWarnings:"Aucun avertissement",noWarningsDesc:"Vous n'avez reçu aucun avertissement de l'administration.",warning:"Avertissement",unknownDate:"Date inconnue",reason:"Motif",unspecifiedReason:"Motif non précisé",adminMessage:"Message de l'administration"},
 en:{likes:"Likes",shares:"Shares",suggestions:"Suggestions",shareCopied:"AfriTok link copied",shareError:"Unable to share AfriTok",creditsInfo:"Project credits are available in the AfriTok repository.",rights:"All rights reserved.",adminRestricted:"Access restricted to administrators.",warnings:"My warnings",warningsLoading:"Loading your warnings...",warningsError:"Unable to load your warnings.",warningsDesc:"View warnings received from the administration.",noWarnings:"No warnings",noWarningsDesc:"You have not received any warnings from the administration.",warning:"Warning",unknownDate:"Unknown date",reason:"Reason",unspecifiedReason:"Reason not specified",adminMessage:"Message from administration"},
 sw:{likes:"Mapendezi",shares:"Shiriki",suggestions:"Mapendekezo",shareCopied:"Kiungo cha AfriTok kimenakiliwa",shareError:"Imeshindikana kushiriki AfriTok",creditsInfo:"Taarifa za wachangiaji zinapatikana kwenye hazina ya AfriTok.",rights:"Haki zote zimehifadhiwa.",adminRestricted:"Ufikiaji umewekewa wasimamizi pekee.",warnings:"Maonyo yangu",warningsLoading:"Inapakia maonyo yako...",warningsError:"Imeshindikana kupakia maonyo.",warningsDesc:"Tazama maonyo uliyopokea kutoka kwa usimamizi.",noWarnings:"Hakuna maonyo",noWarningsDesc:"Hujapokea maonyo yoyote kutoka kwa usimamizi.",warning:"Onyo",unknownDate:"Tarehe haijulikani",reason:"Sababu",unspecifiedReason:"Sababu haijabainishwa",adminMessage:"Ujumbe kutoka kwa usimamizi"},
 yo:{likes:"Awọn ayanfẹ",shares:"Awọn pinpin",suggestions:"Awọn imọran",shareCopied:"Ọna asopọ AfriTok ti daakọ",shareError:"Ko le pin AfriTok",creditsInfo:"Awọn kirẹditi iṣẹ akanṣe wa ninu ibi ipamọ AfriTok.",rights:"Gbogbo ẹtọ wa ni ipamọ.",adminRestricted:"Wiwọle fun awọn alabojuto nikan.",warnings:"Awọn ikilọ mi",warningsLoading:"N gbe awọn ikilọ rẹ...",warningsError:"Ko le gbe awọn ikilọ rẹ.",warningsDesc:"Wo awọn ikilọ ti o gba lati ọdọ iṣakoso.",noWarnings:"Ko si ikilọ",noWarningsDesc:"O ko ti gba ikilọ lati ọdọ iṣakoso.",warning:"Ikilọ",unknownDate:"Ọjọ ti a ko mọ",reason:"Idi",unspecifiedReason:"Idi ko pato",adminMessage:"Ifiranṣẹ lati ọdọ iṣakoso"},
 ha:{likes:"Abubuwan so",shares:"Rarrabawa",suggestions:"Shawarwari",shareCopied:"An kwafi hanyar AfriTok",shareError:"Ba a iya raba AfriTok ba",creditsInfo:"Ana samun bayanan masu bayar da gudummawa a ma'ajiyar AfriTok.",rights:"Duk haƙƙoƙi an kiyaye su.",adminRestricted:"Samun dama ga masu gudanarwa kawai.",warnings:"Gargadi na",warningsLoading:"Ana loda gargadin ku...",warningsError:"Ba a iya loda gargadin ku ba.",warningsDesc:"Duba gargadin da kuka samu daga gudanarwa.",noWarnings:"Babu gargadi",noWarningsDesc:"Ba ku sami gargadi daga gudanarwa ba.",warning:"Gargadi",unknownDate:"Ranar da ba a sani ba",reason:"Dalili",unspecifiedReason:"Ba a bayyana dalili ba",adminMessage:"Saƙo daga gudanarwa"},
 zu:{likes:"Okuthandwayo",shares:"Ukwabelana",suggestions:"Iziphakamiso",shareCopied:"Isixhumanisi se-AfriTok sikopishiwe",shareError:"Ayikwazi ukwabelana nge-AfriTok",creditsInfo:"Amakhredithi ephrojekthi ayatholakala endaweni yokugcina ye-AfriTok.",rights:"Wonke amalungelo agodliwe.",adminRestricted:"Ukufinyelela kugcinelwe abaphathi kuphela.",warnings:"Izexwayiso zami",warningsLoading:"Ilayisha izexwayiso zakho...",warningsError:"Ayikwazi ukulayisha izexwayiso zakho.",warningsDesc:"Buka izexwayiso ozithole kubaphathi.",noWarnings:"Azikho izexwayiso",noWarningsDesc:"Awutholanga zexwayiso kubaphathi.",warning:"Isexwayiso",unknownDate:"Idethi engaziwa",reason:"Isizathu",unspecifiedReason:"Isizathu asicacisiwe",adminMessage:"Umlayezo ovela kubaphathi"}
};
export function useSettingsText(){const{language}=useLanguage();return(key:string,fallback:string)=>extra[language]?.[key]??getSettingsText(language,key,fallback);}
