import { useAuth } from "@/_core/hooks/useAuth";
import { PremiumBadge } from "@/components/PremiumBadge";
import { trpc } from "@/lib/trpc";
import { LiveStatusBadge } from "@/features/live/LiveStatusBadge";
import { useLocation, useRoute } from "wouter";
import { ArrowLeft, Edit3, UserPlus, UserCheck, MoreVertical, MapPin, Eye, X } from "lucide-react";
import { useState } from "react";

interface Video { id:number; userId:number; title:string|null; description:string|null; videoUrl:string; thumbnailUrl:string|null; duration:number|null; views:number|null; likes:number|null; comments:number|null; shares:number|null; favorites:number|null; createdAt:Date; }

export default function Profile() {
 const { user: currentUser } = useAuth(); const [,navigate]=useLocation(); const [,params]=useRoute("/profile/:userId"); const userId=params?.userId?parseInt(params.userId):currentUser?.id; const isOwnProfile=currentUser?.id===userId;
 const [selectedVideoIndex,setSelectedVideoIndex]=useState<number|null>(null); const [activeTab,setActiveTab]=useState<"videos"|"likes"|"favorites">("videos"); const [isFollowing,setIsFollowing]=useState(false); const followMutation=trpc.follower.toggle.useMutation(); const utils=trpc.useUtils(); const deleteVideoMutation=trpc.video.delete.useMutation(); const [showMenu,setShowMenu]=useState(false);
 const userQuery=trpc.user.getProfile.useQuery({userId:userId||0},{enabled:!!userId}); const videosQuery=trpc.video.getByUser.useQuery({userId:userId||0},{enabled:!!userId}); const likedQuery=trpc.like.getMyLikedVideos.useQuery(undefined,{enabled:isOwnProfile&&activeTab==="likes"}); const favoritesQuery=trpc.favorite.getMyVideos.useQuery(undefined,{enabled:isOwnProfile&&activeTab==="favorites"}); const followerCountQuery=trpc.follower.getCount.useQuery({userId:userId||0},{enabled:!!userId});
 if(!userId)return <div className="min-h-screen bg-black text-white flex items-center justify-center"><p>Profil non trouvé</p></div>; if(userQuery.isLoading)return <div className="min-h-screen bg-black text-white flex items-center justify-center"><p>Chargement du profil...</p></div>;
 const profile=userQuery.data; const ownVideos=(videosQuery.data||[]) as Video[]; const followerStats=followerCountQuery.data; const followerCount=typeof followerStats === "number" ? followerStats : (followerStats?.followers ?? 0); const totalLikes=ownVideos.reduce((sum,v)=>sum+(v.likes||0),0); const likedVideos=(likedQuery.data||[]).map((x:any)=>x.video).filter(Boolean) as Video[]; const favoriteVideos=(favoritesQuery.data||[]).map((x:any)=>x.video).filter(Boolean) as Video[]; const filteredVideos=activeTab==="likes"&&isOwnProfile?likedVideos:activeTab==="favorites"&&isOwnProfile?favoriteVideos:ownVideos;
 const handleVideoTap=(i:number)=>{if(isOwnProfile&&activeTab==="videos")setSelectedVideoIndex(i);};
 const closeDeleteMenu=()=>setSelectedVideoIndex(null);
 const handleDeleteVideo=async()=>{const video=selectedVideoIndex===null?null:ownVideos[selectedVideoIndex]; if(!video||!isOwnProfile||activeTab!=="videos")return; try{await deleteVideoMutation.mutateAsync({videoId:video.id}); closeDeleteMenu(); await videosQuery.refetch(); await utils.video.getFeed.invalidate();}catch(e){console.error("[Profile] delete video failed",e); alert("La suppression a échoué. Réessaie.");}};
 return <div className="min-h-screen bg-black text-white pb-20"><header className="sticky top-0 z-40 bg-black/80 backdrop-blur border-b border-gray-800 px-4 py-3 flex items-center justify-between"><button onClick={()=>navigate("/feed")} className="text-white"><ArrowLeft size={24}/></button><h1 className="text-lg font-bold">{profile?.name||"Profil"}</h1><button onClick={()=>setShowMenu(!showMenu)} className="text-white relative"><MoreVertical size={24}/>{showMenu&&<div className="absolute right-0 top-full mt-2 bg-gray-900 rounded-lg shadow-lg z-50 w-48"><button className="block w-full text-left px-4 py-3 hover:bg-gray-800 text-sm border-b border-gray-700">Signaler</button><button className="block w-full text-left px-4 py-3 hover:bg-gray-800 text-sm">Bloquer</button></div>}</button></header>
 <div className="px-4 py-6 border-b border-gray-800"><div className="flex items-start gap-4 mb-4"><div className="relative">{profile?.avatarUrl?<img src={profile.avatarUrl} alt={profile.name||"Profil"} className="w-20 h-20 rounded-full object-cover border-2 border-red-500"/>:<div className="w-20 h-20 rounded-full bg-gradient-to-br from-red-500 to-pink-500 flex items-center justify-center text-white text-2xl font-bold">{profile?.name?.[0]?.toUpperCase()||"U"}</div>}<div className="absolute -bottom-2 left-1/2 -translate-x-1/2"><LiveStatusBadge userId={userId}/></div></div><div className="flex-1"><div className="flex items-center gap-2 flex-wrap"><h2 className="text-2xl font-bold text-white">{profile?.name||"Utilisateur"}</h2><PremiumBadge compact/></div><p className="text-gray-400 text-sm">@{profile?.email?.split("@")[0]||"username"}</p>{profile?.country&&<p className="text-gray-400 text-sm flex items-center gap-1 mt-1"><MapPin size={14}/>{profile.country}</p>}</div>{isOwnProfile?<button onClick={()=>navigate("/edit-profile")} className="bg-red-500 text-white px-4 py-2 rounded-full font-semibold"><Edit3 size={18}/></button>:<button onClick={()=>{if(!userId)return;followMutation.mutate({userId},{onSuccess:r=>setIsFollowing(Boolean(r.following))})}} className="bg-red-500 text-white px-4 py-2 rounded-full font-semibold">{isFollowing?<UserCheck size={18}/>:<UserPlus size={18}/>}</button>}</div>
 <div className="grid grid-cols-3 gap-4 text-center mt-5"><div><p className="text-2xl font-bold">{ownVideos.length}</p><p className="text-gray-400 text-sm">Vidéos</p></div><div><p className="text-2xl font-bold">{totalLikes}</p><p className="text-gray-400 text-sm">Likes</p></div><div><p className="text-2xl font-bold">{followerCount}</p><p className="text-gray-400 text-sm">Abonnés</p></div></div></div>
 <div className="grid grid-cols-3 border-b border-gray-800"><button onClick={()=>setActiveTab("videos")} className={`py-3 ${activeTab==="videos"?"border-b-2 border-red-500":"text-gray-500"}`}>Vidéos</button><button onClick={()=>setActiveTab("likes")} className={`py-3 ${activeTab==="likes"?"border-b-2 border-red-500":"text-gray-500"}`}>J'aime</button><button onClick={()=>setActiveTab("favorites")} className={`py-3 ${activeTab==="favorites"?"border-b-2 border-red-500":"text-gray-500"}`}>Favoris</button></div>
 <div className="grid grid-cols-3 gap-1 p-1">{filteredVideos.map((video,index)=><div key={video.id} className="relative aspect-[9/16] bg-gray-900 overflow-hidden"><button onClick={()=>handleVideoTap(index)} className="w-full h-full"><video src={video.videoUrl} muted playsInline className="w-full h-full object-cover"/></button><div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 to-transparent px-2 pt-5 pb-1 text-left text-xs"><span className="flex items-center gap-1"><Eye size={13}/>{video.views||0} vues</span></div></div>)}</div>
 {selectedVideoIndex!==null&&activeTab==="videos"&&isOwnProfile&&ownVideos[selectedVideoIndex]&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 px-5" role="dialog" aria-modal="true" aria-label="Options de la vidéo"><div className="w-full max-w-sm rounded-2xl bg-gray-900 border border-gray-700 shadow-2xl overflow-hidden"><div className="flex items-center justify-between px-5 py-4 border-b border-gray-700"><h3 className="text-base font-semibold">Options de la vidéo</h3><button onClick={closeDeleteMenu} className="p-1 text-gray-400 hover:text-white" aria-label="Fermer"><X size={20}/></button></div><div className="p-4"><button onClick={handleDeleteVideo} disabled={deleteVideoMutation.isPending} className="w-full rounded-xl bg-red-600 hover:bg-red-500 disabled:opacity-50 px-4 py-3 font-semibold text-white">{deleteVideoMutation.isPending?"Suppression…":"Supprimer"}</button><button onClick={closeDeleteMenu} disabled={deleteVideoMutation.isPending} className="w-full mt-3 rounded-xl bg-gray-800 hover:bg-gray-700 disabled:opacity-50 px-4 py-3 font-semibold text-white">Annuler</button></div></div></div>}
 </div>;
}
