import { useAuth } from "@/_core/hooks/useAuth";
import { MonetizationProgressBar } from "@/components/MonetizationProgressBar";
import { CoinsButton } from "@/components/CoinsButton";
import { WalletButton } from "@/components/WalletButton";
import { PremiumBadge } from "@/components/PremiumBadge";
import { trpc } from "@/lib/trpc";
import { LiveStatusBadge } from "@/features/live/LiveStatusBadge";
import { useLocation, useRoute } from "wouter";
import { ArrowLeft, Play, Heart, MessageCircle, Share2, MapPin, Edit3, UserPlus, UserCheck, MoreVertical, Flame, Lock, Share, Flag, Eye, BarChart3 } from "lucide-react";
import { useState, useRef } from "react";

interface Video { id:number; userId:number; title:string|null; description:string|null; videoUrl:string; thumbnailUrl:string|null; duration:number|null; views:number|null; likes:number|null; comments:number|null; shares:number|null; favorites:number|null; createdAt:Date; }

export default function Profile() {
 const { user: currentUser } = useAuth(); const [,navigate]=useLocation(); const [match,params]=useRoute("/profile/:userId"); const userId=params?.userId?parseInt(params.userId):currentUser?.id; const isOwnProfile=currentUser?.id===userId;
 const [selectedVideoIndex,setSelectedVideoIndex]=useState<number|null>(null); const [activeTab,setActiveTab]=useState<"videos"|"likes"|"favorites">("videos"); const [isFollowing,setIsFollowing]=useState(false); const followMutation=trpc.follower.toggle.useMutation(); const [showMenu,setShowMenu]=useState(false); const [showMonetization,setShowMonetization]=useState(false); const videoRefs=useRef<Record<number,HTMLVideoElement|null>>({});
 const earningsQuery=trpc.earnings.getMyEarnings.useQuery(undefined,{enabled:isOwnProfile,refetchInterval:10000}); const earnings=earningsQuery.data;
 const userQuery=trpc.user.getProfile.useQuery({userId:userId||0},{enabled:!!userId}); const videosQuery=trpc.video.getByUser.useQuery({userId:userId||0},{enabled:!!userId}); const followerCountQuery=trpc.follower.getCount.useQuery({userId:userId||0},{enabled:!!userId});
 if(!userId)return <div className="min-h-screen bg-black text-white flex items-center justify-center"><p>Profil non trouvé</p></div>;
 if(userQuery.isLoading)return <div className="min-h-screen bg-black text-white flex items-center justify-center"><p>Chargement du profil...</p></div>;
 const profile=userQuery.data; const videos=(videosQuery.data||[]) as Video[]; const followerCount=followerCountQuery.data; const totalLikes=videos.reduce((sum,v)=>sum+(v.likes||0),0); const filteredVideos=videos;
 const handleVideoTap=(i:number)=>setSelectedVideoIndex(i); const handleNextVideo=()=>{if(selectedVideoIndex!==null&&selectedVideoIndex<filteredVideos.length-1)setSelectedVideoIndex(selectedVideoIndex+1)}; const handlePrevVideo=()=>{if(selectedVideoIndex!==null&&selectedVideoIndex>0)setSelectedVideoIndex(selectedVideoIndex-1)}; const handleCloseVideo=()=>setSelectedVideoIndex(null);
 return <div className="min-h-screen bg-black text-white pb-20"><header className="sticky top-0 z-40 bg-black/80 backdrop-blur border-b border-gray-800 px-4 py-3 flex items-center justify-between"><button onClick={()=>navigate("/feed")} className="text-white"><ArrowLeft size={24}/></button><h1 className="text-lg font-bold">{profile?.name||"Profil"}</h1><button onClick={()=>setShowMenu(!showMenu)} className="text-white relative"><MoreVertical size={24}/>{showMenu&&<div className="absolute right-0 top-full mt-2 bg-gray-900 rounded-lg shadow-lg z-50 w-48"><button className="block w-full text-left px-4 py-3 hover:bg-gray-800 text-sm border-b border-gray-700">Signaler</button><button className="block w-full text-left px-4 py-3 hover:bg-gray-800 text-sm">Bloquer</button></div>}</button></header>
 <div className="px-4 py-6 border-b border-gray-800"><div className="flex items-start gap-4 mb-4"><div className="relative">{profile?.avatarUrl?<img src={profile.avatarUrl} alt={profile.name||"Profil"} className="w-20 h-20 rounded-full object-cover border-2 border-red-500"/>:<div className="w-20 h-20 rounded-full bg-gradient-to-br from-red-500 to-pink-500 flex items-center justify-center text-white text-2xl font-bold">{profile?.name?.[0]?.toUpperCase()||"U"}</div>}<div className="absolute -bottom-2 left-1/2 -translate-x-1/2"><LiveStatusBadge userId={userId}/></div></div><div className="flex-1"><div className="flex items-center gap-2 flex-wrap"><h2 className="text-2xl font-bold text-white">{profile?.name||"Utilisateur"}</h2><PremiumBadge compact/></div><p className="text-gray-400 text-sm">@{profile?.email?.split("@")[0]||"username"}</p>{profile?.country&&<p className="text-gray-400 text-sm flex items-center gap-1 mt-1"><MapPin size={14}/>{profile.country}</p>}</div>{isOwnProfile?<button onClick={()=>navigate("/edit-profile")} className="bg-red-500 text-white px-4 py-2 rounded-full font-semibold"><Edit3 size={18}/></button>:<button onClick={()=>{if(!userId)return;followMutation.mutate({followingId:userId},{onSuccess:r=>setIsFollowing(Boolean(r))})}} className="bg-red-500 text-white px-4 py-2 rounded-full font-semibold">{isFollowing?<UserCheck size={18}/>:<UserPlus size={18}/>}</button>}</div>
 {isOwnProfile&&<div className="flex gap-2"><button onClick={()=>navigate("/premium/analytics")} className="flex-1 rounded-xl border border-amber-500/40 bg-amber-500/10 px-4 py-3 flex items-center justify-center gap-2 text-amber-400 font-bold"><BarChart3 size={18}/>Analytics Premium</button></div>}
 <div className="grid grid-cols-3 gap-4 text-center mt-5"><div><p className="text-2xl font-bold">{videos.length}</p><p className="text-gray-400 text-sm">Vidéos</p></div><div><p className="text-2xl font-bold">{totalLikes}</p><p className="text-gray-400 text-sm">Likes</p></div><div><p className="text-2xl font-bold">{followerCount||0}</p><p className="text-gray-400 text-sm">Abonnés</p></div></div></div>
 <div className="grid grid-cols-3 border-b border-gray-800"><button onClick={()=>setActiveTab("videos")} className={`py-3 ${activeTab==="videos"?"border-b-2 border-red-500":"text-gray-500"}`}>Vidéos</button><button onClick={()=>setActiveTab("likes")} className={`py-3 ${activeTab==="likes"?"border-b-2 border-red-500":"text-gray-500"}`}>J'aime</button><button onClick={()=>setActiveTab("favorites")} className={`py-3 ${activeTab==="favorites"?"border-b-2 border-red-500":"text-gray-500"}`}>Favoris</button></div><div className="grid grid-cols-3 gap-1 p-1">{filteredVideos.map((video,index)=><button key={video.id} onClick={()=>handleVideoTap(index)} className="aspect-[9/16] bg-gray-900 overflow-hidden"><video ref={el=>{videoRefs.current[video.id]=el}} src={video.videoUrl} muted playsInline className="w-full h-full object-cover"/></button>)}</div></div>;
}