import React,{useCallback,useEffect,useRef}from"react";
import{FaceLandmarker,FilesetResolver,NormalizedLandmark}from"@mediapipe/tasks-vision";
import type{AREffect}from"@/features/ar/ARRegistry";
import{smoothLandmarks}from"./faceUtils";
import{applyBeautyPipeline}from"@/features/beauty/BeautyPipeline";
import{renderFaceEffect}from"@/features/beauty/FaceEffects";
const WASM="/mediapipe/wasm",MODEL="/mediapipe/face_landmarker.task";
type ARStatus="loading"|"ready"|"face"|"no-face"|"error";
function size(c:HTMLCanvasElement){const r=c.getBoundingClientRect(),a=r.width>10&&r.height>10?r.width/r.height:9/16,m=1280;return a<1?{width:Math.max(360,Math.round(m*a)),height:m}:{width:m,height:Math.max(360,Math.round(m/a))}}
function draw(ctx:CanvasRenderingContext2D,v:HTMLVideoElement,w:number,h:number){const s=Math.max(w/v.videoWidth,h/v.videoHeight),dw=v.videoWidth*s,dh=v.videoHeight*s,dx=(w-dw)/2,dy=(h-dh)/2;ctx.drawImage(v,dx,dy,dw,dh);return{s,dx,dy}}
function map(ls:NormalizedLandmark[],v:HTMLVideoElement,w:number,h:number,t:{s:number,dx:number,dy:number}){return ls.map(p=>({...p,x:(p.x*v.videoWidth*t.s+t.dx)/w,y:(p.y*v.videoHeight*t.s+t.dy)/h}))}
export const AREngineMobile:React.FC<{videoRef:React.RefObject<HTMLVideoElement|null>;activeEffect:AREffect|null;filterCss?:string;isRecording?:boolean;canvasRef?:React.RefObject<HTMLCanvasElement|null>;recordingCanvasRef?:React.RefObject<HTMLCanvasElement|null>;onStatusChange?:(s:ARStatus,e?:unknown)=>void;onTrackingFrame?:(f:{video:HTMLVideoElement;landmarks:NormalizedLandmark[];width:number;height:number})=>void}>=(p)=>{
 const local=useRef<HTMLCanvasElement|null>(null),det=useRef<FaceLandmarker|null>(null),prev=useRef<NormalizedLandmark[]|null>(null),raf=useRef(0),lastVideo=useRef(-1),lastDetect=useRef(0),timestamp=useRef(0),status=useRef<ARStatus>("loading"),effect=useRef<AREffect|null>(p.activeEffect),filterCss=useRef<string>(p.filterCss||"none"),post=useRef<HTMLCanvasElement|null>(null);
 useEffect(()=>{effect.current=p.activeEffect},[p.activeEffect]);
 useEffect(()=>{filterCss.current=p.filterCss||"none"},[p.filterCss]);
 const setCanvas=useCallback((n:HTMLCanvasElement|null)=>{local.current=n;if(p.canvasRef)p.canvasRef.current=n},[p.canvasRef]);
 const setStatus=useCallback((s:ARStatus,e?:unknown)=>{if(status.current===s&&s!=="error")return;status.current=s;p.onStatusChange?.(s,e)},[p.onStatusChange]);
 const detect=useCallback((v:HTMLVideoElement,now:number)=>{if(!det.current||v.currentTime<=0||v.currentTime===lastVideo.current||now-lastDetect.current<40)return prev.current;lastDetect.current=now;lastVideo.current=v.currentTime;timestamp.current=Math.max(Math.round(now),timestamp.current+1);try{const r=det.current.detectForVideo(v,timestamp.current),f=r.faceLandmarks?.[0];if(f&&f.length>400){prev.current=smoothLandmarks(f,prev.current,.72);setStatus("face")}else{prev.current=null;setStatus("no-face")}}catch(e){console.error("[AREngineMobile] detect",e);setStatus("error",e)}return prev.current},[setStatus]);
 useEffect(()=>{let dead=false;(async()=>{try{const vision=await FilesetResolver.forVisionTasks(WASM);const d=await FaceLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:MODEL},runningMode:"VIDEO",numFaces:1,minFaceDetectionConfidence:.15,minFacePresenceConfidence:.15,minTrackingConfidence:.15});if(dead){d.close();return}det.current=d;setStatus("ready")}catch(e){console.error("[AREngineMobile] init",e);setStatus("error",e)}})();return()=>{dead=true;det.current?.close();det.current=null;prev.current=null;if(raf.current)cancelAnimationFrame(raf.current)}},[setStatus]);
 const render=useCallback(()=>{const v=p.videoRef.current,c=local.current;if(!v||!c||v.readyState<HTMLMediaElement.HAVE_CURRENT_DATA||!v.videoWidth||!v.videoHeight){raf.current=requestAnimationFrame(render);return}const z=size(c);if(c.width!==z.width||c.height!==z.height){c.width=z.width;c.height=z.height}const ctx=c.getContext("2d",{alpha:true});if(!ctx){raf.current=requestAnimationFrame(render);return}const w=c.width,h=c.height,now=performance.now();ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(w,0);ctx.scale(-1,1);const e=effect.current;let t;try{t=draw(ctx,v,w,h)}catch(err){console.error("[AREngineMobile] draw",err);ctx.restore();raf.current=requestAnimationFrame(render);return}const ls=detect(v,now);ctx.restore();
if(ls?.length){const m=map(ls,v,w,h,t);const mm=m.map(pt=>({...pt,x:1-pt.x}));if(e)try{renderFaceEffect(ctx,mm,w,h,e)}catch(err){console.error("[AREngineMobile] effect",err)}if(e?.beautyConfig)try{applyBeautyPipeline(ctx,mm,w,h,e.beautyConfig)}catch(err){console.error("[AREngineMobile] beauty",err)}p.onTrackingFrame?.({video:v,landmarks:mm,width:w,height:h})}
if(filterCss.current&&filterCss.current!=="none"){if(!post.current)post.current=document.createElement("canvas");const pc=post.current;if(pc.width!==w||pc.height!==h){pc.width=w;pc.height=h}const pctx=pc.getContext("2d");if(pctx){pctx.clearRect(0,0,w,h);pctx.filter=filterCss.current;pctx.drawImage(c,0,0);pctx.filter="none";ctx.clearRect(0,0,w,h);ctx.drawImage(pc,0,0)}}
const recordingCanvas=p.recordingCanvasRef?.current;
if(recordingCanvas&&recordingCanvas.width===w&&recordingCanvas.height===h){const recordingContext=recordingCanvas.getContext("2d",{alpha:true});if(recordingContext){recordingContext.setTransform(1,0,0,1,0,0);recordingContext.globalCompositeOperation="copy";recordingContext.drawImage(c,0,0);recordingContext.globalCompositeOperation="source-over"}}
raf.current=requestAnimationFrame(render)},[p.videoRef,detect,p.onTrackingFrame,p.recordingCanvasRef]);
 useEffect(()=>{raf.current=requestAnimationFrame(render);return()=>{if(raf.current)cancelAnimationFrame(raf.current)}},[render]);
 return <canvas ref={setCanvas} className="absolute inset-0 w-full h-full pointer-events-none z-0" style={{background:"transparent"}}/>;
};
export default AREngineMobile;